### ISSUE TITLE
dears,where is    admin.awl souce code

### ISSUE THREAD

**Issue by introspection3** [anywherelan/awl#122]
dears,where is    admin.awl souce code

**Comment by pymq** [comment]
Hi! GUI part is written in flutter and located here: https://github.com/anywherelan/awl-flutter

It is built for android and web from the same source code.

**Comment by introspection3** [comment]
thank you sir.but why below @pymq 
![image](https://github.com/anywherelan/awl/assets/12368358/cdee9f38-874c-4fb9-8c2c-7b56276b4718)
