### ISSUE TITLE
Hello sir, is it because the code here has not been updated, and why can't I read a Packet locally and send it to the other end of the tun normally according to the NewDevice method?

### ISSUE THREAD

**Issue by introspection3** [anywherelan/awl#129]
Hello sir, is it because the code here has not been updated, and why can't I read a Packet locally and send it to the other end of the tun normally according to the NewDevice method?
I use NewDevice
for packet := range t.device.OutboundChan() {
		 find peer ,then send packet  to peer side by tunnel ,then get the packet,then send to local tun ,but not work.

	}

**Comment by pymq** [comment]
Hello!

I'm sorry, I need more details to help you. Do you want to write some custom code using awl as a library? Or does awl not work for you out of the box?

**Comment by introspection3** [comment]
thank you sir,find the reason ,transport package([]byte),but write byte array
