### ISSUE TITLE
I Can not visit arm node, but arm node can visit me

### ISSUE THREAD

**Issue by cnjmj** [anywherelan/awl#55]
Linux version :
Linux OTCloud_5634 3.10.33 #1 SMP PREEMPT Tue Jun 30 18:57:47 CST 2020 XL-V2.4.4 armv7l GNU/Linux

ping x86 node from arm node:
#ping 10.66.0.3
PING 10.66.0.3 (10.66.0.3): 56 data bytes
64 bytes from 10.66.0.3: seq=0 ttl=128 time=36.732 ms
64 bytes from 10.66.0.3: seq=1 ttl=128 time=38.229 ms
64 bytes from 10.66.0.3: seq=2 ttl=128 time=37.228 ms
^C
--- 10.66.0.3 ping statistics ---
3 packets transmitted, 3 packets received, 0% packet loss

ping arm node from x64 node:
#ping 10.66.0.2
PING 10.66.0.2 (10.66.0.2): 56 data bytes

--- 10.66.0.2 ping statistics ---
3 packets transmitted, 0 packets received, 100% packet loss

maybe arm version have a bug.

**Comment by pymq** [comment]
Hey! thanks for your report

Can you please provide more info about how you setup your two nodes? did you have any logs with `ERROR` or `WARN` level? Did you try to restart both nodes? (just in case) are you sure that you use correct ip address from x64 node? (you can list your known peers with command `./awl cli peers status`)

**Comment by cnjmj** [comment]
> Hey! thanks for your report
> 
> Can you please provide more info about how you setup your two nodes? did you have any logs with `ERROR` or `WARN` level? Did you try to restart both nodes? (just in case) are you sure that you use correct ip address from x64 node? (you can list your known peers with command `./awl cli peers status`)

I want to send log to your mailbox or other contact mode.

**Comment by cnjmj** [comment]
udp        0      0 127.0.0.66:53           0.0.0.0:*                           11400/awl

2022-10-27 10:59:41     WARN    awl/dns send request to upstream dns: read udp 127.0.0.1:46867->127.0.0.1:53: read: connection refused
2022-10-27 10:59:41     WARN    awl/dns send request to upstream dns: read udp 127.0.0.1:40916->127.0.0.1:53: read: connection refused
2022-10-27 10:59:41     WARN    awl/dns send request to upstream dns: read udp 127.0.0.1:44678->127.0.0.1:53: read: connection refused
2022-10-27 10:59:41     WARN    awl/dns send request to upstream dns: read udp 127.0.0.1:39644->127.0.0.1:53: read: connection refused

**Comment by pymq** [comment]
These logs seems fine, dns could not work on some linux configurations, but vpn should work. I have tested awl on arm devices (android with 32 and 64 bit cores), it worked fine. I have no ideas on what could be wrong here, yet, will try to investigate on my personal arm server (raspberry pi) later

I sent a friend request to your arm node

**Comment by cnjmj** [comment]
> These logs seems fine, dns could not work on some linux configurations, but vpn should work. I have tested awl on arm devices (android with 32 and 64 bit cores), it worked fine. I have no ideas on what could be wrong here, yet, will try to investigate on my personal arm server (raspberry pi) later
> 
> I sent a friend request to your arm node

[root@OTCloud_5634:/root]#awl cli peers status
  №  |       PEER       | STATUS  | LAST SEEN  |   NETWORK USAGE    |    CONNECTIONS     | VERSION  
     |                  |         |            |     (↓IN/↑OUT)     | ADDRESS | PROTOCOL |          
-----+------------------+---------+------------+--------------------+--------------------+----------
   1 | maxbook test     | online  | 2022-10-28 | ↓ 0 B/s (1.62 KiB) | through relay      | dev      
     | maxbook_test.awl |         | 18:55:31   | ↑ 0 B/s (1.76 KiB) |                    |          
     | 10.66.0.6        |         |            |                    |                    |          
-----+------------------+---------+------------+--------------------+--------------------+----------
   2 | 10.66.0.5        | offline | 2022-10-28 | ↓ 0 B/s (0 B)      |                    |          
     |                  |         | 15:10:52   | ↑ 0 B/s (0 B)      |                    |          
-----+------------------+---------+------------+--------------------+--------------------+----------
   3 | aaa              | offline | 2022-10-28 | ↓ 0 B/s (0 B)      |                    |          
     | aaa.awl          |         | 14:14:50   | ↑ 0 B/s (0 B)      |                    |          
     | 10.66.0.4        |         |            |                    |                    |          
-----+------------------+---------+------------+--------------------+--------------------+----------
   4 | arm_B            | offline | 2022-10-27 | ↓ 0 B/s (0 B)      |                    |          
     | a.awl            |         | 10:40:39   | ↑ 0 B/s (0 B)      |                    |          
     | 10.66.0.2        |         |            |                    |                    |          
-----+------------------+---------+------------+--------------------+--------------------+----------
   5 | x86              | offline | 2022-10-28 | ↓ 0 B/s (0 B)      |                    |          
     | x86.awl          |         | 15:10:52   | ↑ 0 B/s (0 B)      |                    |          
     | 10.66.0.3        |         |            |                    |                    |          
-----+------------------+---------+------------+--------------------+--------------------+----------
[root@OTCloud:/root]#ping 10.66.0.6
PING 10.66.0.6 (10.66.0.6): 56 data bytes
64 bytes from 10.66.0.6: seq=0 ttl=64 time=329.531 ms
64 bytes from 10.66.0.6: seq=1 ttl=64 time=305.934 ms
64 bytes from 10.66.0.6: seq=2 ttl=64 time=359.749 ms
64 bytes from 10.66.0.6: seq=3 ttl=64 time=389.133 ms
64 bytes from 10.66.0.6: seq=4 ttl=64 time=307.593 ms
^C
--- 10.66.0.6 ping statistics ---
5 packets transmitted, 5 packets received, 0% packet loss
round-trip min/avg/max = 305.934/338.388/389.133 ms

**Comment by pymq** [comment]
I tested and `ping` didn't work for me either

```
$ ping 10.66.0.23
PING 10.66.0.23 (10.66.0.23) 56(84) bytes of data.
^C
--- 10.66.0.23 ping statistics ---
10 packets transmitted, 0 received, 100% packet loss, time 9222ms
```
But I can send you tcp packets, for example via nmap or accessing directly from http `http://10.66.0.23:8800/`
```
$ nmap 10.66.0.23                                 

Nmap scan report for cnjmj-github.awl (10.66.0.23)
Host is up (0.31s latency).
Not shown: 987 closed ports
PORT      STATE    SERVICE
22/tcp    filtered ssh
23/tcp    filtered telnet
8800/tcp  open     sunwebadmin
```

Is it possible that your server has firewall that blocks ping requests? Otherwise there is definitely a bug, thanks for pointing this out!

Could you please try to access your arm node with http or any other tcp protocol from your other node? Seems like this works fine

**Comment by cnjmj** [comment]
[root@OTCloud_5634:/root]#iptables-save
# Generated by iptables-save v1.6.1 on Fri Oct 28 19:17:25 2022
*raw
:PREROUTING ACCEPT [409724363:200607423952]
:OUTPUT ACCEPT [467164086:207471160374]
COMMIT
# Completed on Fri Oct 28 19:17:25 2022
# Generated by iptables-save v1.6.1 on Fri Oct 28 19:17:25 2022
*nat
:PREROUTING ACCEPT [8819386:2633214571]
:INPUT ACCEPT [927052:219732121]
:OUTPUT ACCEPT [35003019:2164021984]
:POSTROUTING ACCEPT [10911259:637527042]
:DOCKER - [0:0]
-A PREROUTING -m addrtype --dst-type LOCAL -j DOCKER
-A OUTPUT ! -d 127.0.0.0/8 -m addrtype --dst-type LOCAL -j DOCKER
-A POSTROUTING -s 172.17.0.0/16 ! -o docker0 -j MASQUERADE
-A POSTROUTING -s 192.168.0.0/16 -j MASQUERADE
-A POSTROUTING -s 10.168.0.0/16 -j MASQUERADE
-A DOCKER -i docker0 -j RETURN
COMMIT
# Completed on Fri Oct 28 19:17:25 2022
# Generated by iptables-save v1.6.1 on Fri Oct 28 19:17:25 2022
*mangle
:PREROUTING ACCEPT [409724363:200607423952]
:INPUT ACCEPT [392275052:176996373657]
:FORWARD ACCEPT [9584916:21199718814]
:OUTPUT ACCEPT [467164103:207471164494]
:POSTROUTING ACCEPT [505267524:235540166408]
COMMIT
# Completed on Fri Oct 28 19:17:25 2022
# Generated by iptables-save v1.6.1 on Fri Oct 28 19:17:25 2022
*filter
:INPUT ACCEPT [6559977:1090459815]
:FORWARD ACCEPT [10073:2164189]
:OUTPUT ACCEPT [10856032:1679807908]
:DOCKER - [0:0]
:DOCKER-ISOLATION - [0:0]
:DOCKER-USER - [0:0]
:GOV_IP_CHAIN - [0:0]
-A INPUT -s 192.168.0.0/16 -j ACCEPT
-A INPUT -s 10.168.0.0/16 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 443 -j DROP
-A INPUT -p tcp -m tcp --dport 22:23 -j DROP
-A INPUT -p tcp -m tcp --dport 9999 -j DROP
-A INPUT -p tcp -m tcp --dport 5299 -j DROP
-A INPUT -p icmp -m icmp --icmp-type 8 -j DROP
-A FORWARD -j DOCKER-USER
-A FORWARD -j DOCKER-ISOLATION
-A FORWARD -o docker0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -o docker0 -j DOCKER
-A FORWARD -i docker0 ! -o docker0 -j ACCEPT
-A FORWARD -i docker0 -o docker0 -j ACCEPT
-A OUTPUT -j GOV_IP_CHAIN
-A DOCKER-ISOLATION -j RETURN
-A DOCKER-USER -j RETURN
-A GOV_IP_CHAIN -m set --match-set gov_ip_ipset dst -j DROP
COMMIT
# Completed on Fri Oct 28 19:17:25 2022

**Comment by cnjmj** [comment]
```
[root@OTCloud:/root]#iptables-save
# Generated by iptables-save v1.6.1 on Fri Oct 28 19:17:25 2022
*raw
:PREROUTING ACCEPT [409724363:200607423952]
:OUTPUT ACCEPT [467164086:207471160374]
COMMIT
# Completed on Fri Oct 28 19:17:25 2022
# Generated by iptables-save v1.6.1 on Fri Oct 28 19:17:25 2022
*nat
:PREROUTING ACCEPT [8819386:2633214571]
:INPUT ACCEPT [927052:219732121]
:OUTPUT ACCEPT [35003019:2164021984]
:POSTROUTING ACCEPT [10911259:637527042]
:DOCKER - [0:0]
-A PREROUTING -m addrtype --dst-type LOCAL -j DOCKER
-A OUTPUT ! -d 127.0.0.0/8 -m addrtype --dst-type LOCAL -j DOCKER
-A POSTROUTING -s 172.17.0.0/16 ! -o docker0 -j MASQUERADE
-A POSTROUTING -s 192.168.0.0/16 -j MASQUERADE
-A POSTROUTING -s 10.168.0.0/16 -j MASQUERADE
-A DOCKER -i docker0 -j RETURN
COMMIT
# Completed on Fri Oct 28 19:17:25 2022
# Generated by iptables-save v1.6.1 on Fri Oct 28 19:17:25 2022
*mangle
:PREROUTING ACCEPT [409724363:200607423952]
:INPUT ACCEPT [392275052:176996373657]
:FORWARD ACCEPT [9584916:21199718814]
:OUTPUT ACCEPT [467164103:207471164494]
:POSTROUTING ACCEPT [505267524:235540166408]
COMMIT
# Completed on Fri Oct 28 19:17:25 2022
# Generated by iptables-save v1.6.1 on Fri Oct 28 19:17:25 2022
*filter
:INPUT ACCEPT [6559977:1090459815]
:FORWARD ACCEPT [10073:2164189]
:OUTPUT ACCEPT [10856032:1679807908]
:DOCKER - [0:0]
:DOCKER-ISOLATION - [0:0]
:DOCKER-USER - [0:0]
:GOV_IP_CHAIN - [0:0]
-A INPUT -s 192.168.0.0/16 -j ACCEPT
-A INPUT -s 10.168.0.0/16 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 443 -j DROP
-A INPUT -p tcp -m tcp --dport 22:23 -j DROP
-A INPUT -p tcp -m tcp --dport 9999 -j DROP
-A INPUT -p tcp -m tcp --dport 5299 -j DROP
-A INPUT -p icmp -m icmp --icmp-type 8 -j DROP
-A FORWARD -j DOCKER-USER
-A FORWARD -j DOCKER-ISOLATION
-A FORWARD -o docker0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -o docker0 -j DOCKER
-A FORWARD -i docker0 ! -o docker0 -j ACCEPT
-A FORWARD -i docker0 -o docker0 -j ACCEPT
-A OUTPUT -j GOV_IP_CHAIN
-A DOCKER-ISOLATION -j RETURN
-A DOCKER-USER -j RETURN
-A GOV_IP_CHAIN -m set --match-set gov_ip_ipset dst -j DROP
COMMIT
# Completed on Fri Oct 28 19:17:25 2022
```

**Comment by cnjmj** [comment]
default is ACCEPT

*filter
:INPUT ACCEPT

**Comment by cnjmj** [comment]
`[root@rancher ~]# ./awl cli peers status
  №  |   PEER    | STATUS | LAST SEEN  |    NETWORK USAGE    |        CONNECTIONS         | VERSION  
     |           |        |            |     (↓IN/↑OUT)      |     ADDRESS | PROTOCOL     |          
-----+-----------+--------+------------+---------------------+----------------------------+----------
   1 | arm       | online | 2022-10-28 | ↓ 0 B/s (1.73 KiB)  | xxx.xxx.xxx.xxx:5403 | quic | v0.5.0   
     | arm.awl   |        | 11:23:04   | ↑ 0 B/s (11.64 KiB) |                            |          
     | 10.66.0.2 |        |            |                     |                            |          
-----+-----------+--------+------------+---------------------+----------------------------+----------
[root@rancher ~]# ping 10.66.0.2
PING 10.66.0.2 (10.66.0.2): 56 data bytes
^C
--- 10.66.0.2 ping statistics ---
5 packets transmitted, 0 packets received, 100% packet loss
[root@rancher ~]# wget http://10.66.0.2
Connecting to 10.66.0.2 (10.66.0.2:80)
wget: can't connect to remote host (10.66.0.2): Connection refused
[root@rancher ~]# wget http://10.66.0.2:9999
Connecting to 10.66.0.2:9999 (10.66.0.2:9999)
^C
[root@rancher ~]# wget http://10.168.28.37:9999
Connecting to 10.168.28.37:9999 (10.168.28.37:9999)
index.html           100% |***************************************************************************************************************************************************************************|   507   0:00:00 ETA

`

**Comment by pymq** [comment]
That's strange, I can't get to 9999 port, but 8800 works fine
```
$ curl http://10.66.0.23:8800                                         
{"sign_rtn":100}%                                                                                                                                                                               
$ curl http://10.66.0.23:9999 
^C
```

**Comment by cnjmj** [comment]
> That's strange, I can't get to 9999 port, but 8800 works fine
> 
> ```
> $ curl http://10.66.0.23:8800                                         
> {"sign_rtn":100}%                                                                                                                                                                               
> $ curl http://10.66.0.23:9999 
> ^C
> ```

now 9999 is ok

**Comment by cnjmj** [comment]
sorry, all is ok, it's my firewall rule denied awl.

-A INPUT -p tcp -m tcp --dport 9999 -j DROP
-A INPUT -p icmp -m icmp --icmp-type 8 -j DROP

**Comment by cnjmj** [comment]
Thank you!

**Comment by pymq** [comment]
Glad it's working for you!

Overall, how's your experience with awl? Does it meet your requirements? Maybe you have any feedback on what we can do better or any feature suggestions?
