### ISSUE TITLE
please compile a awl-linux-mips version

### ISSUE THREAD

**Issue by cnjmj** [anywherelan/awl#56]
I have a padavan router, CPU is MT7621A, need a mips or mipsle platform version
uname -a:
Linux Bsyy 3.4.113 #7 SMP Sun Jan 9 04:53:57 CST 2022 mips GNU/Linux

**Comment by pymq** [comment]
Hey!
I can add mips builds, but I have two concerns:
- you have old linux version (3.4.113), I am not sure it will work there, but we can try
- routers usually have very small RAM and permanent storage, but overall fine CPU. Awl binary will be around 30 MB, do your router have this amount of free storage? and it will require about ~60 MB RAM

Also, I had in mind that awl should be installed on end devices like linux servers or personal devices (laptops, mobiles), what case do you have to use awl on your router?

**Comment by cnjmj** [comment]
iptables -A POSTROUTING -o awl0 -j MASQUERADE

use awl on router for the lan device can visit the external awl node.
my router have 512MB ram, and exists external sd card.

**Comment by pymq** [comment]
Oh, that's great! I'll add a mips build over the weekend

**Comment by cnjmj** [comment]
thank you!

**Comment by pymq** [comment]
Could you please test this build, it's not in a release yet, but still
[awl-linux-mips-v0.5.0-5-g0d9c3804.tar.gz](https://github.com/anywherelan/awl/files/9893428/awl-linux-mips-v0.5.0-5-g0d9c3804.tar.gz)

**Comment by cnjmj** [comment]
Thank you. test result is:

`[Bsyy /media/AiDisk_a1/anywherelan]# cat /proc/cpuinfo 
system type             : MediaTek MT7621 SoC
processor               : 0
cpu model               : MIPS 1004Kc V2.15
BogoMIPS                : 583.68
wait instruction        : yes
microsecond timers      : yes
tlb_entries             : 32
extra interrupt vector  : yes
hardware watchpoint     : yes, count: 4, address/irw mask: [0x0000, 0x0000, 0x0003, 0x0003]
ASEs implemented        : mips16 dsp mt
shadow register sets    : 1
kscratch registers      : 0
core                    : 0
VPE                     : 0
VCED exceptions         : not available
VCEI exceptions         : not available

processor               : 1
cpu model               : MIPS 1004Kc V2.15
BogoMIPS                : 583.68
wait instruction        : yes
microsecond timers      : yes
tlb_entries             : 32
extra interrupt vector  : yes
hardware watchpoint     : yes, count: 4, address/irw mask: [0x0000, 0x0000, 0x0000, 0x0000]
ASEs implemented        : mips16 dsp mt
shadow register sets    : 1
kscratch registers      : 0
core                    : 0
VPE                     : 1
VCED exceptions         : not available
VCEI exceptions         : not available

processor               : 2
cpu model               : MIPS 1004Kc V2.15
BogoMIPS                : 583.68
wait instruction        : yes
microsecond timers      : yes
tlb_entries             : 32
extra interrupt vector  : yes
hardware watchpoint     : yes, count: 4, address/irw mask: [0x0000, 0x0000, 0x0000, 0x0000]
ASEs implemented        : mips16 dsp mt
shadow register sets    : 1
kscratch registers      : 0
core                    : 1
VPE                     : 0
VCED exceptions         : not available
VCEI exceptions         : not available

processor               : 3
cpu model               : MIPS 1004Kc V2.15
BogoMIPS                : 583.68
wait instruction        : yes
microsecond timers      : yes
tlb_entries             : 32
extra interrupt vector  : yes
hardware watchpoint     : yes, count: 4, address/irw mask: [0x0000, 0x0000, 0x0000, 0x0000]
ASEs implemented        : mips16 dsp mt
shadow register sets    : 1
kscratch registers      : 0
core                    : 1
VPE                     : 1
VCED exceptions         : not available
VCEI exceptions         : not available

[Bsyy /media/AiDisk_a1/anywherelan]# uname -a
Linux Bsyy 3.4.113 #7 SMP Sun Jan 9 04:53:57 CST 2022 mips GNU/Linux
[Bsyy /media/AiDisk_a1/anywherelan]# ll awl_mips 
-rwxrwxrwx    1 admin    root      30081024 Oct 29 18:07 awl_mips*
[Bsyy /media/AiDisk_a1/anywherelan]# ./awl_mips 
./awl_mips: line 1: syntax error: unexpected "("
[Bsyy /media/AiDisk_a1/anywherelan]# `

maybe the platform is mipsle.

**Comment by cnjmj** [comment]
MT7621 platform, some application can use mips version, some software requires mipsle version, I don't know where their specific differences are.

**Comment by pymq** [comment]
Here is build for mipsle
[awl-linux-mipsle-v0.5.0-5-g5a94c198.tar.gz](https://github.com/anywherelan/awl/files/9893551/awl-linux-mipsle-v0.5.0-5-g5a94c198.tar.gz)

**Comment by cnjmj** [comment]
Now it runs correctly. It's a perfect application. Thank you!

**Comment by cnjmj** [comment]
I use awl to connect network devices with no public network address at different locations to achieve mutual access and resource sharing. The router is deployed to enable direct access to all awl nodes within the LAN. Awl runs very stably, and the network speed is also very good. In use, it is found that you cannot use awl to access LAN devices, even if nat/masquerade is enabled on the router. I don't know whether it is the setting problem, or whether awl does not support forwarding or nat
