### ISSUE TITLE
how to make direct connections in this repo

### ISSUE THREAD

**Issue by neophack** [anywherelan/awl#61]
some repo like openp2p has good direct connections

**Comment by neophack** [comment]
https://github.com/zfunnily/hole-punching-go-libp2p

**Comment by pymq** [comment]
I'm sorry, I still don't have a good tutorial how to setup all this.

Basically, if you want to test on desktop, you need to download awl-tray binary, run it as root (or administrator), open web interface (by clicking on the system tray icon --> Open Web UI. Or just go to http://localhost.awl:8639/). Do this on both your devices. Then you need to add new peer (see button in the interface), peer ID you can get by clicking "Show ID". Later you need to accept invitation on the second peer's admin UI and after all this you can interconnect between your devices. IP and domain address you can see in the interface. Awl works on IP level, so you can ping your devices or access its TCP/UDP ports.

Feel free to ask here if you have any questions.

**Comment by neophack** [comment]
Direct connect is peer to peer and disconnect server,  through public relay is too slow.
you can try this repo https://github.com/openp2p-cn/openp2p, it has high probability to use direct connect.
![Screenshot from 2022-11-03 09-04-18](https://user-images.githubusercontent.com/12814250/199629790-636f6f18-98dc-4835-9a03-d88a42951827.png)

**Comment by pymq** [comment]
Awl tries to create direct connections the same way as openp2p. In current release we use rather old libraries, after #52 it should be much better, stay tuned

**Comment by pymq** [comment]
@neophack fyi it should be much better with latest release

**Comment by neophack** [comment]
Test some networks, quic can work normally, but some networks are still not as good as openp2p

**Comment by neophack** [comment]
I am quite satisfied now

**Comment by pymq** [comment]
Thanks for testing!

@neophack could you please provide more information about networks in which awl can't do direct connections? I thought it should be the same
