### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by dillfrescott** [anywherelan/awl#75]
This project is awesome! Is there a way to enable a peer to auto accept requests?

**Comment by dillfrescott** [comment]
Also, is there a way for a node in a network to have the same ip for everyone?

**Comment by pymq** [comment]
Hi, thanks!

> Is there a way to enable a peer to auto accept requests?

This is not documented yet, but you can manually set `autoAcceptAuthRequests` param to true in your config file (see README where config file is located or in logs, it is printed on server start). You need to stop server before editing config.

Note that this is not secure: anyone will be able to auto connect to your peer. This feature was intended to use in "public servers". You can enable this flag, add peers and then disable it

> Also, is there a way for a node in a network to have the same ip for everyone?

Unfortunately, no. I have plans on feature like "group of peers with shared access to each other", but it's not there yet.

For now, you can manually edit config file, you need to search for `knownPeers` group and edit `ipAddr` for each peer.

Hope that helps, any feedback is welcome

**Comment by dillfrescott** [comment]
Okay! Thank you!

**Comment by dillfrescott** [comment]
@pymq is there any way you could implement a rough form of a static ip function? I would love to use this app but it makes it nearly impossible without static ip's for my usecases.

**Comment by pymq** [comment]
@dillfrescott what usecases do you have? I'm asking because I think awl DNS should work just fine for most of them

**Comment by dillfrescott** [comment]
The dns name depends on what the peer names the connection though, right?

Basically I'm trying to point cloudflare DNS to an in network ip, so only the people that have the server as a peer can access the web server essentially.

**Comment by pymq** [comment]
> The dns name depends on what the peer names the connection though, right?

Yes,  by default dns name equals to peer name, but dns name could be changed independently of peer name

<details> 
  <summary>Screenshot from web gui </summary>
  
![image](https://github.com/anywherelan/awl/assets/26528802/41250eea-41fc-4690-841b-51d6f64f368f)

</details>

> Basically I'm trying to point cloudflare DNS to an in network ip, so only the people that have the server as a peer can access the web server essentially.

Interesting, this is necessary to have more human readable address and to easily send links to it to someone?

Do your peer with web server has peer name set? I can propose feature more easily to implement: all peers broadcast their name (as opposite to alias, that you can change) and their names will be set as dns addresses.

Example: peer A has name "something". You added it with an alias "tester". And you can access it with "something.awl" AND "tester.awl". Currently you can access it only with "tester.awl".

**Comment by dillfrescott** [comment]
I think that could work! Sounds good!

**Comment by pymq** [comment]
@dillfrescott I totally forgot, you can address peers like `{peer_id}.awl` - this way you don't need to set anything special in your config in every peer, and you can set this name in dns redirect or something

**Comment by dillfrescott** [comment]
Oh! Okay!

**Comment by dillfrescott** [comment]
@pymq the peer id .awl thing isnt working at all :/

**Comment by dillfrescott** [comment]
It says no such address known

**Comment by pymq** [comment]
@dillfrescott That's interesting. Could you please provide more details about your system: what OS, version?

Also, could you try with my peer, invite `12d3koowjmujt9b5t1umzgzjlv5yg2viuuf4qjmn65tsrxzgs1p8` and go to http://12d3koowjmujt9b5t1umzgzjlv5yg2viuuf4qjmn65tsrxzgs1p8.awl/ , it should open page with librespeed

**Comment by dillfrescott** [comment]
@pymq Sure! I am on Windows 11 and I'm just using the latest windows tray binary from releases.

![Screenshot 2023-05-14 143302](https://github.com/anywherelan/awl/assets/56714680/12d29f02-c005-4c52-a6a4-7e97711b54a2)

**Comment by pymq** [comment]
@dillfrescott Sorry, wrong peer id. Try this one: `12D3KooWJMUjt9b5T1umzgzjLv5yG2ViuuF4qjmN65tsRXZGS1p8`

But anyway it's probably bug in awl dns, I didn't test on windows 11, only on 10

**Comment by dillfrescott** [comment]
Ok i sent the request

**Comment by pymq** [comment]
It should accept instantly

**Comment by dillfrescott** [comment]
![image](https://github.com/anywherelan/awl/assets/56714680/7f56ed08-d2e6-416e-9684-91419bba233e)

I directly copy-pasted it too

**Comment by dillfrescott** [comment]
I think my questions have been sufficiently answered so I will close this issue. :)
