### ISSUE TITLE
QR not readable

### ISSUE THREAD

**Issue by Rrisinglight** [anywherelan/awl#89]
https://github.com/anywherelan/awl/assets/58220666/510e3f9e-5c6c-4844-999e-e8165adbb30b

Google pixel 2;
Android 11;

**Comment by pymq** [comment]
Can't reproduce on two my devices, but I found relevant issue upstream: https://github.com/juliuscanute/qr_code_scanner/issues/415

Should be fixed with this workaround in next release, thanks for your report!
