### ISSUE TITLE
admin.awl not secure

### ISSUE THREAD

**Issue by KemalErtas** [anywherelan/awl#98]
admin.awl page is not shown on chrome page becouse of "Not Secure" warning on Win10

**Comment by pymq** [comment]
Hi @KemalErtas 

That's strange, I tested in Windows 11 VM in Edge and Chrome and it's working as expected. Could you please send a screenshot?

Is there any way to add it to exceptions list?

I can assure that it's "Secure" enough - admin.awl is only accessible on your computer.

As a workaround you can open http://127.0.0.66/ - it's the same page

**Comment by KemalErtas** [comment]
![Not Secure](https://github.com/anywherelan/awl/assets/109876032/85710d12-8e25-4375-b67d-3df1ed4ba083)

**Comment by KemalErtas** [comment]
With  http://127.0.0.66/  , its empty page.

**Comment by pymq** [comment]
What awl version do you use? (link to the file from releases page)

Could you please test with different browser?

In both URLs it should be `http`, not `https`

You could also try `http://127.0.0.1:8639`

**Comment by KemalErtas** [comment]
with http://127.0.0.1:8639/ , its solved and anywherelan page appear.
thanks a lot.

**Comment by pymq** [comment]
glad it's worked

but it's still a weird bug for me

could you please check if this setting is enabled in your Chrome? `HTTPS-First mode`
https://support.google.com/chrome/answer/10468685?sjid=10617222637730967650-EU#https-only-mode

And also send a screenshot of the full page when you go to the http://admin.awl

**Comment by KemalErtas** [comment]
![Not routed](https://github.com/anywherelan/awl/assets/109876032/9ff299dc-5946-4604-8a28-98cca10c2730)

**Comment by pymq** [comment]
I'll look into it

**Comment by pymq** [comment]
About white screen - could you open web console (F12 in browser) and show errors if there is any. Unfortunately I can't reproduce this myself

**Comment by pymq** [comment]
Oh no, I mean when tab is open press F12 to open developer tools like this: https://wd.imgix.net/image/admin/dpOohQpnFAKdK0JpVvuv.png?auto=format&w=1600

**Comment by KemalErtas** [comment]
MS Edge F12 Consolu
![Ms Edge F12 Console Capture](https://github.com/anywherelan/awl/assets/109876032/4e51cb2c-7ec0-4076-aa0b-0aa4297ca57e)

Ms Edge  F12 Issues
![Ms Edge F12 Issues](https://github.com/anywherelan/awl/assets/109876032/2c91af78-2e61-4f01-8066-32efa22c66f1)

**Comment by pymq** [comment]
Thanks! I still have no clue how is it possible, but we are getting closer

After restarting awl, do you have logs like `starting web server on http://127.0.0.66:80` or `unable to bind web server on admin host`?

You can see logs from the web interface in `Server logs` on the left

**Comment by KemalErtas** [comment]
![Server log](https://github.com/anywherelan/awl/assets/109876032/ca51ebcf-5651-4343-97df-ea13448fd64a)

**Comment by pymq** [comment]
Thanks, I see the problem now

One more thing: could you please press `Open Web UI` from awl system tray icon - what page will be opened: `http://127.0.0.1:8639` or `http://admin.awl`? I guess it should be 127.0.0.1:8639 in your case

**Comment by KemalErtas** [comment]
http://admin.awl again

**Comment by pymq** [comment]
Do you have any antivirus software installed?

Any chance you have another program that uses 80 port? you can check it using terminal command `netstat -ano | find ":80"`

**Comment by KemalErtas** [comment]
Yes I have Kaspersky Anti Virus.

![Capture](https://github.com/anywherelan/awl/assets/109876032/93821a2d-c98d-470d-97c2-477fc220d58f)

**Comment by KemalErtas** [comment]
Netstat after starting awl server.

![Capture](https://github.com/anywherelan/awl/assets/109876032/58cfe96c-f607-4b33-aae9-0f8dd575feea)
